# Generated by Django 5.1.4 on 2025-01-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_collection_collectionitem_collection_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='person_images/'),
        ),
    ]
