# Generated by Django 5.2.11 on 2026-02-21 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_person_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or scam'), ('harassment', 'Harassment'), ('hate_speech', 'Hate speech'), ('violence', 'Violence or threat'), ('misinformation', 'Misinformation'), ('other', 'Other')], max_length=32)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed'), ('actioned', 'Actioned')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.comment')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.person')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_report_status_9a134a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('person__isnull', False), ('comment__isnull', True)), models.Q(('person__isnull', True), ('comment__isnull', False)), _connector='OR'), name='report_single_target'), models.UniqueConstraint(condition=models.Q(('person__isnull', False)), fields=('reporter', 'person'), name='unique_person_report_per_user'), models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('reporter', 'comment'), name='unique_comment_report_per_user')],
            },
        ),
    ]
