# Generated by Django 5.2.11 on 2026-03-25 21:38

from django.db import migrations, models
from django.db.models import Avg, Count


def populate_person_rating_caches(apps, schema_editor):
    Person = apps.get_model("core", "Person")
    Rating = apps.get_model("core", "Rating")

    aggregates = {
        row["person_id"]: row
        for row in Rating.objects.values("person_id").annotate(
            average=Avg("score"),
            count=Count("id"),
        )
    }

    persons_to_update = []
    for person in Person.objects.all():
        person_aggregate = aggregates.get(person.pk, {})
        person.ratings_average_cached = float(person_aggregate.get("average") or 0.0)
        person.ratings_count_cached = person_aggregate.get("count") or 0
        persons_to_update.append(person)

    if persons_to_update:
        Person.objects.bulk_update(
            persons_to_update,
            ["ratings_average_cached", "ratings_count_cached"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comment_hidden_at_comment_hidden_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ratings_average_cached',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='person',
            name='ratings_count_cached',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.RunPython(
            populate_person_rating_caches,
            migrations.RunPython.noop,
        ),
    ]
